### ISSUE TITLE
Dodać opinię na podst. listu referencyjnego od PekaoFS

### ISSUE THREAD

**Issue by sulmar** [sulmar/sulmar.github.io#115]
[list referencyjny Pekao FS.pdf](https://github.com/sulmar/sulmar-homepage/files/14855030/list.referencyjny.Pekao.FS.pdf)

**Comment by sulmar** [comment]
Proponuję skorzystać z tego fragmentu:
![image](https://github.com/sulmar/sulmar.github.io/assets/779025/923de02e-5697-4af1-9a41-d2c72ae970c1)

**Comment by jszufa** [comment]
jakiego autora wpisać?
author: Pekao Financial Services ?

**Comment by sulmar** [comment]
Mirosław Chmiel, Pekao Financial Services

**Comment by jszufa** [comment]
![image](https://github.com/sulmar/sulmar.github.io/assets/118739912/af89d5b9-1a86-4dec-a429-622437baa1e3)
