### ISSUE TITLE
Dodać opinię 

### ISSUE THREAD

**Issue by sulmar** [sulmar/sulmar.github.io#119]
_Szkolenie z zagadnień komunikacji z urządzeniami fizycznymi poprzez protokoły SCPI i ModBus prowadzone przez pana Marcina Suleckiego, było przygotowane wzorcowo, jak garnitur szyty na miarę. Podejście całkowicie z
oczekiwaniami klienta. Przygotowanie merytoryczne i praktyczne bardzo dobre, błyskawiczne
rozwiązywanie wszystkich wątpliwości podczas szkolenia. Wsparcie trenera po szkoleniu
Polecam i zachęcam do udziału._

Witold Majda
Technolog - Wojskowe Zakłady Lotnicze Nr 1 S.A.

szkolenie: .NET ModBus

**Comment by jszufa** [comment]
slug: dotnet ?

**Comment by jszufa** [comment]
![image](https://github.com/sulmar/sulmar.github.io/assets/118739912/fed03536-e973-4d7c-a59c-4f258108c257)
