### ISSUE TITLE
Poprawić opis strony w meta

### ISSUE THREAD

**Issue by sulmar** [sulmar/sulmar.github.io#122]
`<meta name="description" content="My first VuePress Site">`

**Comment by sulmar** [comment]
Proponuję jako content: `Szkolenia dla programistów z zakresu .NET, SQL, REDIS i Crystal Reports`

**Comment by jszufa** [comment]
Poprawiłem:
![image](https://github.com/sulmar/sulmar.github.io/assets/118739912/c69c4d57-34bc-467f-8f86-4131b7c5a2ed)
