### ISSUE TITLE
Przenieść stronę na https://sulmar.github.io

### ISSUE THREAD

**Issue by sulmar** [sulmar/sulmar.github.io#123]

**Comment by sulmar** [comment]
- [x] Zmieniłem nazwę repo na 'sulmar.github.io'

**Comment by sulmar** [comment]
Rozjechały się style:
![image](https://github.com/sulmar/sulmar.github.io/assets/779025/be019b57-f811-451f-aad7-e6cf692e9f1d)

**Comment by jszufa** [comment]
już działa :)
one nie były zahardcodowane tylko w vuepress można ustawić base:
![image](https://github.com/sulmar/sulmar.github.io/assets/118739912/848bcff1-fc19-458d-836e-3c0bf74dc4b3)
i potem używać tego np. tak:
![image](https://github.com/sulmar/sulmar.github.io/assets/118739912/d95286f4-2c08-43f0-a02c-ad49670b825a)
