### ISSUE TITLE
Podpiąć sulmar.github.io pod www.sulmar.pl

### ISSUE THREAD

**Issue by sulmar** [sulmar/sulmar.github.io#125]

**Comment by sulmar** [comment]
Zależne od #123

**Comment by jszufa** [comment]
Tutaj dokumentacja z github na ten temat: https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site

**Comment by sulmar** [comment]
Skonfigurowałem. Działa :)
