### ISSUE TITLE
W rozmiarze mobile ucięty kafelek szkolenia

### ISSUE THREAD

**Issue by sulmar** [sulmar/sulmar.github.io#132]
Niby drobiazg.

![image](https://github.com/sulmar/sulmar.github.io/assets/779025/ad880ad9-61e1-46da-a038-b6503b2944b1)

Proponuję ustawić tak wysokość w rozmiarze mobile, aby mieściły się wszystkie 4 kursy.

**Comment by jszufa** [comment]
Ok, cenna uwaga, poprawiłem - wyświetlają się równo 4.
![image](https://github.com/sulmar/sulmar.github.io/assets/118739912/340fed5e-d406-4ee8-92aa-b95d717cada4)
