### ISSUE TITLE
Dodać id do sekcji testimonials aby można było dodać hyperlink #testimonials

### ISSUE THREAD

**Issue by sulmar** [sulmar/sulmar.github.io#133]

**Comment by jszufa** [comment]
![image](https://github.com/sulmar/sulmar.github.io/assets/118739912/5d48a6fa-38d7-4702-994c-a9bdea624b43)

**Comment by sulmar** [comment]
Na stronie raczej nie będziemy umieszczać linka w menu ale dzięki temu mogę komuś wysłać linka mailem.
