### ISSUE TITLE
Testy jednostkowe w C# - przesunięta treść względem punktatorów

### ISSUE THREAD

**Issue by sulmar** [sulmar/sulmar.github.io#136]
![image](https://github.com/sulmar/sulmar.github.io/assets/779025/6252844c-7707-41b7-92b7-1e4f34263f8b)

**Comment by sulmar** [comment]
Co ciekawe, problem dotyczy tylko tego szkolenia. Na pozostałych jest ok.

**Comment by jszufa** [comment]
W programie były odstępy między kolejnymi podpunktami i nie łapało tego jako jednej listy.
![image](https://github.com/sulmar/sulmar.github.io/assets/118739912/596eebac-53d5-4fb5-9fb0-d91060e042cc)

Jak się usunie odstępy to jest ok.
![image](https://github.com/sulmar/sulmar.github.io/assets/118739912/4109010a-28e7-4911-927d-7368206f6110)
![image](https://github.com/sulmar/sulmar.github.io/assets/118739912/64392fb2-8dc4-45f1-bfb6-1a538a646e0b)
