### ISSUE TITLE
Poprawić wyświetlanie opinii przy długim tekście autora

### ISSUE THREAD

**Issue by jszufa** [sulmar/sulmar.github.io#137]
![image](https://github.com/sulmar/sulmar.github.io/assets/118739912/66f06af8-b879-4ed1-bbfe-6b89cc98a15a)

**Comment by sulmar** [comment]
albo usuń S.A. ;-)

**Comment by sulmar** [comment]
usuń funkcję

**Comment by jszufa** [comment]
dobre pomysły- tak zrobiłem.
Skróciłem teź pekao financial services do pekao fs.
Dodałem odpowiednie zawijanie na mniejszych rozdzielczościach.
![image](https://github.com/sulmar/sulmar.github.io/assets/118739912/f4352f58-28ca-4758-8645-56281ca7ae23)
![image](https://github.com/sulmar/sulmar.github.io/assets/118739912/b9aa918e-909f-4e67-9f83-050e3f4a7f87)
