### ISSUE TITLE
Szablon szkolenia - przy pośredniej szerokości rozjeżdżają się ikonki 

### ISSUE THREAD

**Issue by sulmar** [sulmar/sulmar.github.io#138]
![image](https://github.com/sulmar/sulmar.github.io/assets/779025/7f702724-ae8e-425f-8183-edce9e21f997)

Przy mniejszym rozmiarze (mobile) jest już dobrze. Proponuję przy rozmiarze pośrednim ułożyć ikonki w 2 kolumnach.

**Comment by sulmar** [comment]
Dokładnie tak jest zrobione z numerami:
![image](https://github.com/sulmar/sulmar.github.io/assets/779025/09ea747b-f786-427a-9b09-e3ed62d47b08)

**Comment by jszufa** [comment]
poprawiłem:
![image](https://github.com/sulmar/sulmar.github.io/assets/118739912/bfc4b15d-35ae-4362-ba1b-e0a7ad8ae3cc)
