### ISSUE TITLE
Dodać identyfikator do formularza kontaktowego zgodnie z zaleceniem 

### ISSUE THREAD

**Issue by sulmar** [sulmar/sulmar.github.io#149]
![image](https://github.com/sulmar/sulmar.github.io/assets/779025/e769afd4-e469-4a29-a93f-409b8d63cb23)

**Comment by jszufa** [comment]
To zalecenie dotyczy pola wyszukiwania, do którego nie mam bezpośredniego dostępu (pochodzi z wtyczki).
Mógłbym dodać id za pomocą javascripta, pytanie czy dodawać, czy zignorować ten problem?

**Comment by sulmar** [comment]
W takim przypadku to zignorujmy.
