### ISSUE TITLE
Elementy nagłówków nie pojawiają się w kolejności malejącej

### ISSUE THREAD

**Issue by sulmar** [sulmar/sulmar.github.io#151]
![image](https://github.com/sulmar/sulmar.github.io/assets/779025/473bef73-bdd4-4a98-b289-26ed44348b9d)

na podst.
https://pagespeed.web.dev/analysis/https-sulmar-github-io/bhzq36fqcp?form_factor=desktop

To ma wpływ na jakość strony, a co za tym idzie SEO.

**Comment by sulmar** [comment]
Proponuję sprawdzić, czy hierarchia nagłówków H1, H2...H6 jest ciągła i malejąca

**Comment by jszufa** [comment]
poprawiłem: 
![image](https://github.com/sulmar/sulmar.github.io/assets/118739912/f309be3b-3e09-4512-a506-adc44ccdf3f1)
